name: Publish Java Package to Maven Central

on:
  release:
    types: [ published ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JAVA and Maven Central Repository
        uses: actions/setup-java@v3
        with:
          java-version: 19.0.0
          distribution: 'temurin'
          java-package: 'jdk'
          cache: 'maven'
          server-id: ossrh
      - name: Import GPG Signing Key
        uses: crazy-max/ghaction-import-gpg@v5.0.0
        with:
          gpg_private_key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
      - name: Release To Maven Central
        run: |
          mvn -B -U \
            -Prelease \
            javadoc:jar \
            source:jar \
            -s settings.xml \
            -Dgpg.passphrase=${{ secrets.MAVEN_GPG_PASSPHRASE }} \
            deploy
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}